/* eslint-disable */

import { Country } from "src/app/classes/country";

export const countryNamesInGerman: Country[] = [
    {"name":"Afghanistan","code":"af"},
    {"name":"Ägypten","code":"eg"},
    {"name":"Albanien","code":"al"},
    {"name":"Algerien","code":"dz"},
    {"name":"Andorra","code":"ad"},
    {"name":"Angola","code":"ao"},
    {"name":"Antigua und Barbuda","code":"ag"},
    {"name":"Äquatorialguinea","code":"gq"},
    {"name":"Argentinien","code":"ar"},
    {"name":"Armenien","code":"am"},
    {"name":"Aserbaidschan","code":"az"},
    {"name":"Äthiopien","code":"et"},
    {"name":"Australien","code":"au"},
    {"name":"Bahamas","code":"bs"},
    {"name":"Bahrain","code":"bh"},
    {"name":"Bangladesch","code":"bd"},
    {"name":"Barbados","code":"bb"},
    {"name":"Belarus","code":"by"},
    {"name":"Belgien","code":"be"},
    {"name":"Belize","code":"bz"},
    {"name":"Benin","code":"bj"},
    {"name":"Bhutan","code":"bt"},
    {"name":"Bolivien","code":"bo"},
    {"name":"Bosnien und Herzegowina","code":"ba"},
    {"name":"Botswana","code":"bw"},
    {"name":"Brasilien","code":"br"},
    {"name":"Brunei","code":"bn"},
    {"name":"Bulgarien","code":"bg"},
    {"name":"Burkina Faso","code":"bf"},
    {"name":"Burundi","code":"bi"},
    {"name":"Chile","code":"cl"},
    {"name":"Volksrepublik China","code":"cn"},
    {"name":"Costa Rica","code":"cr"},
    {"name":"Dänemark","code":"dk"},
    {"name":"Deutschland","code":"de"},
    {"name":"Dominica","code":"dm"},
    {"name":"Dominikanische Republik","code":"do"},
    {"name":"Dschibuti","code":"dj"},
    {"name":"Ecuador","code":"ec"},
    {"name":"Elfenbeinküste","code":"ci"},
    {"name":"El Salvador","code":"sv"},
    {"name":"Eritrea","code":"er"},
    {"name":"Estland","code":"ee"},
    {"name":"Eswatini","code":"sz"},
    {"name":"Fidschi","code":"fj"},
    {"name":"Finnland","code":"fi"},
    {"name":"Frankreich","code":"fr"},
    {"name":"Gabun","code":"ga"},
    {"name":"Gambia","code":"gm"},
    {"name":"Georgien","code":"ge"},
    {"name":"Ghana","code":"gh"},
    {"name":"Grenada","code":"gd"},
    {"name":"Griechenland","code":"gr"},
    {"name":"Guatemala","code":"gt"},
    {"name":"Guinea","code":"gn"},
    {"name":"Guinea-Bissau","code":"gw"},
    {"name":"Guyana","code":"gy"},
    {"name":"Haiti","code":"ht"},
    {"name":"Honduras","code":"hn"},
    {"name":"Indien","code":"in"},
    {"name":"Indonesien","code":"id"},
    {"name":"Irak","code":"iq"},
    {"name":"Iran","code":"ir"},
    {"name":"Irland","code":"ie"},
    {"name":"Island","code":"is"},
    {"name":"Israel","code":"il"},
    {"name":"Italien","code":"it"},
    {"name":"Jamaika","code":"jm"},
    {"name":"Japan","code":"jp"},
    {"name":"Jemen","code":"ye"},
    {"name":"Jordanien","code":"jo"},
    {"name":"Kambodscha","code":"kh"},
    {"name":"Kamerun","code":"cm"},
    {"name":"Kanada","code":"ca"},
    {"name":"Kap Verde","code":"cv"},
    {"name":"Kasachstan","code":"kz"},
    {"name":"Katar","code":"qa"},
    {"name":"Kenia","code":"ke"},
    {"name":"Kirgisistan","code":"kg"},
    {"name":"Kiribati","code":"ki"},
    {"name":"Kolumbien","code":"co"},
    {"name":"Komoren","code":"km"},
    {"name":"Kongo, Demokratische Republik","code":"cd"},
    {"name":"Kongo, Republik","code":"cg"},
    {"name":"Korea, Nord","code":"kp"},
    {"name":"Korea, Süd","code":"kr"},
    {"name":"Kroatien","code":"hr"},
    {"name":"Kuba","code":"cu"},
    {"name":"Kuwait","code":"kw"},
    {"name":"Laos","code":"la"},
    {"name":"Lesotho","code":"ls"},
    {"name":"Lettland","code":"lv"},
    {"name":"Libanon","code":"lb"},
    {"name":"Liberia","code":"lr"},
    {"name":"Libyen","code":"ly"},
    {"name":"Liechtenstein","code":"li"},
    {"name":"Litauen","code":"lt"},
    {"name":"Luxemburg","code":"lu"},
    {"name":"Madagaskar","code":"mg"},
    {"name":"Malawi","code":"mw"},
    {"name":"Malaysia","code":"my"},
    {"name":"Malediven","code":"mv"},
    {"name":"Mali","code":"ml"},
    {"name":"Malta","code":"mt"},
    {"name":"Marokko","code":"ma"},
    {"name":"Marshallinseln","code":"mh"},
    {"name":"Mauretanien","code":"mr"},
    {"name":"Mauritius","code":"mu"},
    {"name":"Mexiko","code":"mx"},
    {"name":"Mikronesien","code":"fm"},
    {"name":"Moldau","code":"md"},
    {"name":"Monaco","code":"mc"},
    {"name":"Mongolei","code":"mn"},
    {"name":"Montenegro","code":"me"},
    {"name":"Mosambik","code":"mz"},
    {"name":"Myanmar","code":"mm"},
    {"name":"Namibia","code":"na"},
    {"name":"Nauru","code":"nr"},
    {"name":"Nepal","code":"np"},
    {"name":"Neuseeland","code":"nz"},
    {"name":"Nicaragua","code":"ni"},
    {"name":"Niederlande","code":"nl"},
    {"name":"Niger","code":"ne"},
    {"name":"Nigeria","code":"ng"},
    {"name":"Nordmazedonien","code":"mk"},
    {"name":"Norwegen","code":"no"},
    {"name":"Oman","code":"om"},
    {"name":"Österreich","code":"at"},
    {"name":"Osttimor","code":"tl"},
    {"name":"Pakistan","code":"pk"},
    {"name":"Palau","code":"pw"},
    {"name":"Panama","code":"pa"},
    {"name":"Papua-Neuguinea","code":"pg"},
    {"name":"Paraguay","code":"py"},
    {"name":"Peru","code":"pe"},
    {"name":"Philippinen","code":"ph"},
    {"name":"Polen","code":"pl"},
    {"name":"Portugal","code":"pt"},
    {"name":"Ruanda","code":"rw"},
    {"name":"Rumänien","code":"ro"},
    {"name":"Russland","code":"ru"},
    {"name":"Salomonen","code":"sb"},
    {"name":"Sambia","code":"zm"},
    {"name":"Samoa","code":"ws"},
    {"name":"San Marino","code":"sm"},
    {"name":"São Tomé und Príncipe","code":"st"},
    {"name":"Saudi-Arabien","code":"sa"},
    {"name":"Schweden","code":"se"},
    {"name":"Schweiz","code":"ch"},
    {"name":"Senegal","code":"sn"},
    {"name":"Serbien","code":"rs"},
    {"name":"Seychellen","code":"sc"},
    {"name":"Sierra Leone","code":"sl"},
    {"name":"Simbabwe","code":"zw"},
    {"name":"Singapur","code":"sg"},
    {"name":"Slowakei","code":"sk"},
    {"name":"Slowenien","code":"si"},
    {"name":"Somalia","code":"so"},
    {"name":"Spanien","code":"es"},
    {"name":"Sri Lanka","code":"lk"},
    {"name":"St. Kitts und Nevis","code":"kn"},
    {"name":"St. Lucia","code":"lc"},
    {"name":"St. Vincent und die Grenadinen","code":"vc"},
    {"name":"Südafrika","code":"za"},
    {"name":"Sudan","code":"sd"},
    {"name":"Südsudan","code":"ss"},
    {"name":"Suriname","code":"sr"},
    {"name":"Syrien","code":"sy"},
    {"name":"Tadschikistan","code":"tj"},
    {"name":"Tansania","code":"tz"},
    {"name":"Thailand","code":"th"},
    {"name":"Togo","code":"tg"},
    {"name":"Tonga","code":"to"},
    {"name":"Trinidad und Tobago","code":"tt"},
    {"name":"Tschad","code":"td"},
    {"name":"Tschechien","code":"cz"},
    {"name":"Tunesien","code":"tn"},
    {"name":"Türkei","code":"tr"},
    {"name":"Turkmenistan","code":"tm"},
    {"name":"Tuvalu","code":"tv"},
    {"name":"Uganda","code":"ug"},
    {"name":"Ukraine","code":"ua"},
    {"name":"Ungarn","code":"hu"},
    {"name":"Uruguay","code":"uy"},
    {"name":"Usbekistan","code":"uz"},
    {"name":"Vanuatu","code":"vu"},
    {"name":"Venezuela","code":"ve"},
    {"name":"Vereinigte Arabische Emirate","code":"ae"},
    {"name":"Vereinigte Staaten","code":"us"},
    {"name":"Vereinigtes Königreich","code":"gb"},
    {"name":"Vietnam","code":"vn"},
    {"name":"Zentral­afrikanische Republik","code":"cf"},
    {"name":"Zypern","code":"cy"}
    ]
