image: node:14

stages:
  - Build
  - Test
  - Deploy

build:
  stage: Build
  image: trion/ng-cli
  before_script:
    - npm ci
  script:
    - ng build
  artifacts:
    paths:
      - dist/

test:nglint:
  stage: Test
  image: trion/ng-cli
  allow_failure: true
  before_script:
    - npm ci
  script:
    - ng lint

deploy:
  stage: Deploy
  only:
    - master
  image: trion/ng-cli
  before_script:
    - npm install
    - npm install -g serverless
    - npm install serverless-single-page-app-plugin
    - npm install serverless-s3-sync
    - ng build
  script:
    - serverless s3sync
  after_script:
    - serverless domainInfo

clear_cloudfront_cache:
  stage: Deploy
  only:
    - master
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws cloudfront create-invalidation --distribution-id E2JV8CIUEA5Y6P --paths "/*"
