image: node:14

stages:
  - build
  - test
  - deploy

# build:
#   image: trion/ng-cli
#   before_script:
#     - npm ci
#   script:
#     - ng build
#   artifacts:
#     paths:
#       - dist/
#   tags:
#     - frontend
#     - angular


variables:
  CLI_VERSION: 12.1.2

# test:nglint:
#   stage: test
#   image: trion/ng-cli:${CLI_VERSION}
#   allow_failure: true
#   before_script:
#     - npm ci
#   script:
#     - ng lint
#   tags:
#     - frontend
#     - angular

deploy:
  stage: deploy
  image: trion/ng-cli
  # only:
  #   - master
  before_script:
    - npm install
    - npm install -g serverless
    - npm install serverless-single-page-app-plugin
    - npm install serverless-s3-sync
    - ng build
  script:
    - serverless s3sync
  tags:
    - frontend
    - angular
